### ISSUE TITLE
game crashes while starting up the server for the first time after installation

### ISSUE THREAD

**Issue by LandonHM1** [kntrel/Underilla#15]
**(warning i cant code at all so it could be somthing simple)** 
I installed underilla using the step by step guide but upon first start up of the server it always seems to crash and give me this:

java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R3/generator/CraftChunkData
	at com.jkantrell.mc.underilla.spigot.generation.UnderillaChunkGenerator.generateSurface(UnderillaChunkGenerator.java:55)
	at org.bukkit.craftbukkit.v1_20_R2.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:146)
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$8(ChunkStatus.java:86)
	at net.minecraft.world.level.chunk.ChunkStatus$d.doWork(ChunkStatus.java:300)
	at net.minecraft.world.level.chunk.ChunkStatus.a(ChunkStatus.java:228)
	at net.minecraft.server.level.PlayerChunkMap.lambda$33(PlayerChunkMap.java:737)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.level.PlayerChunkMap.lambda$32(PlayerChunkMap.java:727)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:62)
	at net.minecraft.util.thread.ThreadedMailbox.h(SourceFile:91)
	at net.minecraft.util.thread.ThreadedMailbox.a(SourceFile:146)
	at net.minecraft.util.thread.ThreadedMailbox.run(SourceFile:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R3.generator.CraftChunkData
	
	as stated it could be somthing simple but i cant code or read code lol.

**Comment by HydrolienF** [comment]
Witch Minecraft version are you using ?
Error speak about 1.20.2 and 1.19.4, one of it is probably your version and the other one the expected version.

You could try a more up to date version that work on 1.19.4 to 1.20.4 on my fork (https://github.com/HydrolienF/Underilla/releases/tag/1.4.1)
